### ISSUE TITLE
`unknown opcode`

### ISSUE THREAD

**Issue by hughperkins** [fringsoo/pragmatics_game#3]
```
python run_experiments.py
...
  File "/home/ubuntu/pragmatics_game/utils.py", line 136, in <lambda>
    conv_2 = crosschannelnormalization()(conv_2)
SystemError: unknown opcode
```

**Comment by hughperkins** [comment]
```
Traceback (most recent call last):
  File "run_experiments.py", line 19, in <module>
    agent = Agents(config_dict)
  File "/persist/git/pragmatics_game/agents.py", line 1221, in __init__
    self.config)
  File "/persist/git/pragmatics_game/agent_speaker.py", line 397, in __init__
    super(PaperSpeakerNetwork_rnn_conv, self).__init__(modelname, optfilename, lr, entropy_coefficient, config)
  File "/persist/git/pragmatics_game/agent_speaker.py", line 28, in __init__
    self.initialize_model()
  File "/persist/git/pragmatics_game/agent_speaker.py", line 430, in initialize_model
    self.load()
  File "/persist/git/pragmatics_game/agent_speaker.py", line 43, in load
    self.speaker_model = load_model(self.modelname)
  File "/persist/.pyenv/versions/pragmaticspy36/lib/python3.6/site-packages/keras/models.py", line 270, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/persist/.pyenv/versions/pragmaticspy36/lib/python3.6/site-packages/keras/models.py", line 347, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/persist/.pyenv/versions/pragmaticspy36/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/persist/.pyenv/versions/pragmaticspy36/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "/persist/.pyenv/versions/pragmaticspy36/lib/python3.6/site-packages/keras/engine/topology.py", line 2525, in from_config
    process_layer(layer_data)
  File "/persist/.pyenv/versions/pragmaticspy36/lib/python3.6/site-packages/keras/engine/topology.py", line 2511, in process_layer
    custom_objects=custom_objects)
  File "/persist/.pyenv/versions/pragmaticspy36/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/persist/.pyenv/versions/pragmaticspy36/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "/persist/.pyenv/versions/pragmaticspy36/lib/python3.6/site-packages/keras/engine/topology.py", line 2535, in from_config
    process_node(layer, node_data)
  File "/persist/.pyenv/versions/pragmaticspy36/lib/python3.6/site-packages/keras/engine/topology.py", line 2492, in process_node
    layer(input_tensors[0], **kwargs)
  File "/persist/.pyenv/versions/pragmaticspy36/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/persist/.pyenv/versions/pragmaticspy36/lib/python3.6/site-packages/keras/layers/core.py", line 685, in call
    return self.function(inputs, **arguments)
  File "/home/ubuntu/pragmatics_game/utils.py", line 136, in <lambda>
    conv_2 = crosschannelnormalization()(conv_2)
SystemError: unknown opcode
```

**Comment by hughperkins** [comment]
worked around this by not loading a model.
