### ISSUE TITLE
`IndexError: index 3 is out of bounds for axis 0 with size 2`

### ISSUE THREAD

**Issue by hughperkins** [fringsoo/pragmatics_game#4]
Using following run_experiments.py:
```
agent = Agents(config_dict)

#agent.pretrain_fit_conv()

# agent.fit()

#agent.set_virtual_origin()
# agent.set_virtual_real()
#agent.train_virtual_listener()
#agent.train_virtual_speaker()
# agent.check_virtual_listener()
# agent.check_virtual_speaker()

agent.predict()
```

I get:

```
/opt/pyenv/versions/asr/lib/python3.6/site-packages/keras/models.py:282: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Traceback (most recent call last):                           | Elapsed Time: 0:00:00 ETA:  --:--:--   0.00  B/s
  File "run_experiments.py", line 32, in <module>
    agent.predict()
  File "/gfs/nlp/hp/git/pragmatics_game/agents.py", line 1063, in predict
    reward, target_input, speaker_message, chosen_target_idx, mp, cs, _, _ = utils_prag_sample(self.speaker_model, self.listener_model, test_example, 0)
  File "/gfs/nlp/hp/git/pragmatics_game/agents.py", line 315, in utils_prag_sample
    samples = utils_sample_message_for_a_candidate(speaker_model, target_input)
  File "/gfs/nlp/hp/git/pragmatics_game/agents.py", line 274, in utils_sample_message_for_a_candidate
    s = utils_mask_message(s, speaker_model.config['maskdigit'], speaker_model.config['mask'])
  File "/gfs/nlp/hp/git/pragmatics_game/agents.py", line 262, in utils_mask_message
    message[maskdigit] = mask
IndexError: index 3 is out of bounds for axis 0 with size 2
```

**Comment by hughperkins** [comment]
(Note: I think I also hacked the code to not try to load a pre-trained model)

**Comment by hughperkins** [comment]
```
(mltf) mltf ~/git/pragmatics_game (main|…2△4)$ git diff
diff --git a/.vscode/settings.json b/.vscode/settings.json
index 7a73a41..e4d8a71 100644
--- a/.vscode/settings.json
+++ b/.vscode/settings.json
@@ -1,2 +1,3 @@
 {
+    "python.pythonPath": "/Users/hp/.pyenv/versions/3.7.7/envs/ulfs/bin/python"
 }
\ No newline at end of file
diff --git a/agents.py b/agents.py
index f284b89..b17ac4a 100644
--- a/agents.py
+++ b/agents.py
@@ -1228,7 +1228,7 @@ class Agents_rnnconv(Agents_dense):
                                                                                                                
        self.config)
                
        def init_dataset(self):
-               if not os.path.exists(self.config['modelpath']):
+               if not os.path.exists(self.config['modelpath']) and self.config['modelpath'] != '':
                        os.mkdir(self.config['modelpath'])
 
                datafile = os.path.join('datadir', 'bullet_data_generator.pkl')
diff --git a/config.py b/config.py
index 73aef9e..b0265c5 100644
--- a/config.py
+++ b/config.py
@@ -88,8 +88,9 @@ agent_config_dict_rnnbasic = {
 
 agent_config_dict_rnnconv = {  
        ###################################fixed for a model###################################
-       "modelpath": os.path.join("models", "model_pixel_rnnconv_alpha17_maxlength5"),
+       # "modelpath": os.path.join("models", "model_pixel_rnnconv_alpha17_maxlength5"),
        #"modelpath": os.path.join("models", "new_model_pixel_rnnconv_alpha17_maxlength5"),
+       "modelpath": "",
 
        
        #"agent_amount": 10,
diff --git a/run_experiments.py b/run_experiments.py
index 8b97cd4..9da75ca 100644
--- a/run_experiments.py
+++ b/run_experiments.py
@@ -20,14 +20,14 @@ agent = Agents(config_dict)
 
 #agent.pretrain_fit_conv()
 
-#agent.fit()
+# agent.fit()
 
 #agent.set_virtual_origin()
-agent.set_virtual_real()
+# agent.set_virtual_real()
 #agent.train_virtual_listener()
 #agent.train_virtual_speaker()
-agent.check_virtual_listener()
-agent.check_virtual_speaker()
+# agent.check_virtual_listener()
+# agent.check_virtual_speaker()
 
 agent.predict()
```

**Comment by hughperkins** [comment]
我觉得可能是因为这个部分：
```
			if md != self.config['alphabet_size'] - 1:
				action.append(md)
				d += 1
			else:
				break 
```
因为每一个s没有稳定的长度。所以那个maskdigits有时候不存在:
```
utils_mask_message(s, speaker_model.config['maskdigit'], speaker_model.config['mask'])
```
然后
```
	message[maskdigit] = mask
```
我在`utils_mask_message`家一个行，突然没有问题：
```
def utils_mask_message(message, maskdigit, mask):
	maskdigit = [d for d in maskdigit if d < len(message)]
	message[maskdigit] = mask
	return message
```
